[project]
name = "Desktop Mate Avatar Loader Autoinstall"
version = "1.0.0"
description = "Auto installer for Desktop Mate Avatar Loader mod"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
    "vdf>=3.4",
]
